spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payments}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    # hikari
    hikari:
      idle-timeout: 10000
      minimum-idle: 2
      maximum-poll-size: 10
---
#jpa
spring:
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #    open-in-view: true
---
# flyway
spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 1
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-sufix: .sql